apiVersion: grafana.aws.jet.crossplane.io/v1alpha2
kind: Workspace
metadata:
  name: sample-workspace
spec:
  forProvider:
    region: us-east-1
    authenticationProviders: 
      - AWS_SSO
    accountAccessType: "CURRENT_ACCOUNT"
    roleArnRef:
      name: sample-grafana-role
    organizationalUnits:
      - ou-in2k-3hj06d00
    permissionType: "SERVICE_MANAGED"
    dataSources:
      - CLOUDWATCH
      - PROMETHEUS
      - AMAZON_OPENSEARCH_SERVICE
