---
apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: SecurityGroup
metadata:
  name: sample-sg
spec:
  forProvider:
    region: us-west-1
    description: Cluster communication with worker nodes
    name: sample-sg
    vpcIdRef:
      name: sample-vpc
  providerConfigRef:
    name: default
