---
apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: SecurityGroupRule
metadata:
  name: sample-sgr
spec:
  forProvider:
    region: us-west-1
    securityGroupIdRef:
      name: sample-sg
    type: ingress      
    protocol: tcp
    fromPort: 443
    toPort: 443
    cidrBlocks:
      - "172.16.0.0/16" 
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: SecurityGroupRule
metadata:
  name: sample-egress-sgr
spec:
  forProvider:
    region: us-west-1
    securityGroupIdRef:
      name: sample-sg
    type: egress            
    protocol: "-1"
    fromPort: 0
    toPort: 0
    cidrBlocks:
      - "0.0.0.0/0" 
  providerConfigRef:
    name: default
